variables:
  GIT_SUBMODULE_STRATEGY: recursive

stages:
  - test
  - test_tag

###################################################################################################
# Run tests
###################################################################################################
run_test:
  stage: test
  tags:
    - shell
  script:
    - source ./setup_env
    - cd tests
    - ./run_tests.sh
    - ./run_test_boot.sh

run_test_tag:
  stage: test_tag
  tags:
    - shell
  only:
    - tags
  when: always
  script:
    - source ./setup_env
    - cd tests
    - ./run_tests.sh
    - ./run_test_boot.sh
    - ./run_test_release.sh
