- name : clear
  id : 0x00
  input :
  output :

############################################
# SHA
############################################
- name : sha512
  id : 0x50
  input :
  output :

- name : sha512_init
  id : 0x51
  input :
  output :

- name : sha512_update
  id : 0x52
  input :
    - name : data0
      address : 0x0020
    - name : data1
      address : 0x0040
    - name : data2
      address : 0x0060
    - name : data3
      address : 0x0080
  output :

- name : sha512_final
  id : 0x53
  input :
    - name : data0
      address : 0x0020
    - name : data1
      address : 0x0040
    - name : data2
      address : 0x0060
    - name : data3
      address : 0x0080
  output :
    - name : digest0
      address : 0x1020
    - name : digest1
      address : 0x1040

############################################
# ECC Key Gen/Store
############################################
- name : ecc_key
  id : 0x20
  input :
  output :
    - name : result
      address : 0x0

- name : ecc_key_gen
  id : 0x21
  input :
  output :

- name : ecc_key_store
  id : 0x22
  input :
    - name : k
      address : 0x10
  output :

- name : ecc_key_read
  id : 0x23
  input :
  output :
    - name : pub_key
      address : 0x10

- name : ecc_key_erase
  id : 0x24
  input :
  output :

############################################
# Secure Channel
############################################
- name : x25519
  id : 0x10
  input:
  output:

- name : x25519_kpair_gen
  id : 0x11
  input:
  output:
    - name : etpub
      address : 0x1020

- name : x25519_sc_et_eh
  id : 0x12
  input:
    - name : ehpub
      address : 0x0020
  output:
    - name : x1
      address : 0x1020

- name : x25519_sc_et_sh
  id : 0x13
  input:
    - name : slot
      address : 0x0020
  output:
    - name : r2
      address : 0x1020

- name : x25519_sc_st_eh
  id : 0x14
  input:
  output:
    - name : r3
      address : 0x1020

############################################
# EdDSA
############################################
- name : eddsa
  id : 0x40
  input :
  output :

- name : eddsa_set_context
  id : 0x41
  input :
    - name : sch
      address : 0x00A0
    - name : scn
      address : 0x00C0
  output :

- name : eddsa_nonce_init
  id : 0x42
  input :
  output :

- name : eddsa_nonce_update
  id : 0x43
  input :
    - name : message
      address : 0x00
  output :

- name : eddsa_nonce_finish
  id : 0x42
  input :
    - name : message
      address : 0x00
  output :

- name : eddsa_R_part
  id : 0x45
  input :
  output :

- name : eddsa_e_prep
  id : 0x46
  input :
    - name : message
      address : 0x00
  output :

- name : eddsa_e_update
  id : 0x47
  input :
    - name : message
      address : 0x00
  output :

- name : eddsa_e_finish
  id : 0x48
  input :
    - name : message
      address : 0x00
  output :

- name : eddsa_finish
  id : 0x49
  input :
  output :
    - name : r
      address : 0x10
    - name : s
      address : 0x10

- name : eddsa_verify
  id : 0x4A
  input :
    - name : r
      address : 0x0020
    - name : s
      address : 0x0040
    - name : pubkey
      address : 0x0060
    - name : message0
      address : 0x0080
    - name : message1
      address : 0x00A0
  output :
    - name : result
      address : 0x1020

############################################
# ECDSA
############################################

- name : ecdsa_sign
  id : 0x31
  input :
    - name : message
      address : 0x10
    - name : sch
      address : 0x00A0
    - name : scn
      address : 0x00C0
  output :
    - name : r
      address : 0x10
    - name : s
      address : 0x10

############################################
# Debug
############################################

- name : x25519_dbg
  id : 0x9F
  input :
    - name : priv
      address : 0x0020
    - name : pub
      address : 0x0040
  output :
    - name : r
      address : 0x1020

- name : curve25519_rpg
  id : 0xD0
  input :
  output :

- name : ed25519_rpg
  id : 0xD1
  input :
  output :
    